repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-check
        args: [--fix]
        files: ^(pi|hub)/
        types_or: [python, pyi]
      - id: ruff-format
        files: ^(pi|hub)/
        types_or: [python, pyi]
