/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/addresses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Paginated, filterable list of addresses */
    get: operations["list_addresses_addresses_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/addresses/{address}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Single-address summary */
    get: operations["address_detail_addresses__address__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/addresses/{address}/observations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Observation timeline for one address */
    get: operations["address_observations_addresses__address__observations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness check */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/observations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Recent observations across all scanners */
    get: operations["list_observations_observations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/scanners": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List scanners with totals */
    get: operations["list_scanners_scanners_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/scanners/{scanner_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Per-scanner detail with recent ingests */
    get: operations["scanner_detail_scanners__scanner_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Unified search across addresses, names, vendors, and services */
    get: operations["search_search_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/stats/hourly": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Observations per scanner per UTC hour */
    get: operations["hourly_stats_hourly_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/stats/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Global counts and time range */
    get: operations["overview_stats_overview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/stats/vendors": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Manufacturer-data company-ID breakdown */
    get: operations["vendors_stats_vendors_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AddressSummary */
    AddressSummary: {
      /**
       * Address
       * @description BLE MAC address as observed.
       */
      address: string;
      /**
       * First Observed Utc
       * Format: date-time
       */
      first_observed_utc: string;
      /**
       * Last Observed Utc
       * Format: date-time
       */
      last_observed_utc: string;
      /** Local Name */
      local_name: string | null;
      /** Name */
      name: string | null;
      /** Observations */
      observations: number;
      /** Scanners */
      scanners: string[];
      /** Services */
      services: string[];
      /** Vendors */
      vendors: string[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Health */
    Health: {
      /**
       * Archive Modified At Utc
       * Format: date-time
       */
      archive_modified_at_utc: string;
      /** Archive Path */
      archive_path: string;
      /** Archive Size Bytes */
      archive_size_bytes: number;
      /** Last Ingest At Utc */
      last_ingest_at_utc: string | null;
      /** Package Version */
      package_version: string;
      /**
       * Status
       * @default ok
       * @constant
       */
      status: "ok";
    };
    /** HourlyBucket */
    HourlyBucket: {
      /** Distinct Addresses */
      distinct_addresses: number;
      /**
       * Hour Utc
       * Format: date-time
       */
      hour_utc: string;
      /** Observations */
      observations: number;
      /** Scanner Id */
      scanner_id: string;
    };
    /** IngestRecord */
    IngestRecord: {
      /**
       * Ingested At Utc
       * Format: date-time
       */
      ingested_at_utc: string;
      /** Pi Package Version */
      pi_package_version: string;
      /** Rows In Snapshot */
      rows_in_snapshot: number;
      /** Rows Inserted */
      rows_inserted: number;
      /** Rows Skipped */
      rows_skipped: number;
      /**
       * Snapshot Taken At Utc
       * Format: date-time
       */
      snapshot_taken_at_utc: string;
    };
    /** Observation */
    Observation: {
      /** Address */
      address: string;
      /** Local Name */
      local_name: string | null;
      /** Manufacturer Data */
      manufacturer_data: {
        [key: string]: string;
      };
      /** Name */
      name: string | null;
      /**
       * Observed At Utc
       * Format: date-time
       */
      observed_at_utc: string;
      /** Rssi */
      rssi: number | null;
      /** Scanner Id */
      scanner_id: string;
      /** Service Uuids */
      service_uuids: string[];
    };
    /** Overview */
    Overview: {
      /** Distinct Addresses */
      distinct_addresses: number;
      /** First Observed Utc */
      first_observed_utc: string | null;
      /** Last Ingest At Utc */
      last_ingest_at_utc: string | null;
      /** Last Observed Utc */
      last_observed_utc: string | null;
      /** Scanner Count */
      scanner_count: number;
      /** Total Observations */
      total_observations: number;
    };
    /** Page[AddressSummary] */
    Page_AddressSummary_: {
      /** Items */
      items: components["schemas"]["AddressSummary"][];
      /**
       * Next Cursor
       * @description Opaque cursor; pass to ?cursor= for the next page.
       */
      next_cursor?: string | null;
    };
    /** Page[Observation] */
    Page_Observation_: {
      /** Items */
      items: components["schemas"]["Observation"][];
      /**
       * Next Cursor
       * @description Opaque cursor; pass to ?cursor= for the next page.
       */
      next_cursor?: string | null;
    };
    /** ScannerDetail */
    ScannerDetail: {
      /** Distinct Addresses */
      distinct_addresses: number;
      /** First Observed Utc */
      first_observed_utc: string | null;
      /** Hostname */
      hostname?: string | null;
      /** Last Observed Utc */
      last_observed_utc: string | null;
      /** Observations */
      observations: number;
      /** Recent Ingests */
      recent_ingests?: components["schemas"]["IngestRecord"][];
      /** Scanner Id */
      scanner_id: string;
    };
    /** ScannerSummary */
    ScannerSummary: {
      /** Distinct Addresses */
      distinct_addresses: number;
      /** First Observed Utc */
      first_observed_utc: string | null;
      /** Last Observed Utc */
      last_observed_utc: string | null;
      /** Observations */
      observations: number;
      /** Scanner Id */
      scanner_id: string;
    };
    /** SearchHit */
    SearchHit: {
      /** Address */
      address?: string | null;
      /** Detail */
      detail?: string | null;
      /**
       * Kind
       * @enum {string}
       */
      kind: "address" | "name" | "vendor" | "service";
      /** Label */
      label: string;
      /** Last Observed Utc */
      last_observed_utc?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VendorBucket */
    VendorBucket: {
      /** Company Id Hex */
      company_id_hex: string;
      /** Distinct Addresses */
      distinct_addresses: number;
      /** Observations */
      observations: number;
      /** Vendor */
      vendor: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_addresses_addresses_get: {
    parameters: {
      query?: {
        /** @description Substring match on address, name, or local_name. */
        q?: string | null;
        scanner_id?: string | null;
        /** @description Only addresses last seen at or after this UTC instant. */
        seen_since?: string | null;
        sort?: "last_seen" | "first_seen" | "observations";
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_AddressSummary_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  address_detail_addresses__address__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AddressSummary"];
        };
      };
      /** @description Address not present in archive */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  address_observations_addresses__address__observations_get: {
    parameters: {
      query?: {
        since?: string | null;
        until?: string | null;
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path: {
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_Observation_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  list_observations_observations_get: {
    parameters: {
      query?: {
        scanner_id?: string | null;
        address?: string | null;
        since?: string | null;
        until?: string | null;
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_Observation_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_scanners_scanners_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScannerSummary"][];
        };
      };
    };
  };
  scanner_detail_scanners__scanner_id__get: {
    parameters: {
      query?: {
        recent_ingests?: number;
      };
      header?: never;
      path: {
        scanner_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScannerDetail"];
        };
      };
      /** @description Unknown scanner_id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_search_get: {
    parameters: {
      query: {
        q: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchHit"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  hourly_stats_hourly_get: {
    parameters: {
      query?: {
        since?: string | null;
        until?: string | null;
        scanner_id?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HourlyBucket"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  overview_stats_overview_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Overview"];
        };
      };
    };
  };
  vendors_stats_vendors_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VendorBucket"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
